org: diegorivadeneyra
service: api-web-scraping-igp

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::572536330236:role/LabRole
  region: us-east-1

functions:
  scrape_igp:
    handler: scrape_igp.lambda_handler
    package:
      include:
        - scrape_igp.py
        - requests/**
    events:
      - http:
          path: /scrape/igp
          method: get
          cors: true
          integration: lambda
